---
- hosts: all
  become: true
  vars:
    nameserver1: 41.228.228.228
    nameserver2: 41.228.229.229
  tasks:
  - lineinfile:
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4['interface'] }}"
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {regexp: "^DNS1=", line: "DNS1={{ nameserver1 }}"}
      - {regexp: "^DNS2=", line: "DNS2={{ nameserver2 }}"}
    notify:
      - restart network service
  handlers:
  - name: restart network service
    command: "systemctl restart network"
